version: '2'

services: 
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./srv/web:/srv/web
            - ./default.conf:/etc/nginx/conf.d/default.conf
        networks: 
            - web-network-01
    php:
        image: php:7-fpm
        volumes:
            - ./srv/web:/srv/web
        networks: 
            - web-network-01
#    db:
#        image: mariadb:latest
#        command: mysqld
#        volumes:
#            - ./dbdata:/var/lib/mysql
#        environment:
#            - MYSQL_DATABASE=db
#            - MYSQL_ROOT_PASSWORD=supersecretpassword
#        networks: 
#            - web-network-01
networks: 
    web-network-01:
        driver: bridge